#!/bin/bash

# Set the Finder label color
# should these be in ""?
argc=$#
argv=$@

# buffer the input data
ary=()

while read data; do
	ary=( "${ary[@]}" "$data" )
done

if [ $ary ]; then
	argc=$(( argc+1 ))
	if [ $argv ]; then
		argv="$argv $ary"
	else 
		argv="$ary"
	fi
fi

if [ $argc -lt 1 ]; then
	echo "USAGE: label [0-7] file1 [file2] ..."
	echo "Sets the Finder label (color) for files"
	echo "Default colors:"
	echo " 0  No color"
	echo " 1  Orange"
	echo " 2  Red"
	echo " 3  Yellow"
	echo " 4  Blue"
	echo " 5  Purple"
	echo " 6  Green"
	echo " 7  Gray"
else
	if [ $argc -lt 2 ]; then
		argv="4 $argv"
	fi
	
	osascript - "$@" << EOF
	on run argv
		set labelIndex to (item 1 of argv as number)
		repeat with i from 2 to (count of argv)
			tell application "Finder"
				set theFile to POSIX file (item i of argv) as alias
				set label index of theFile to labelIndex
			end tell
		end repeat
	end run
EOF
fi