#!/bin/bash

# Sets the Finder label color
if [ $# -lt 1 ]; then
	echo "Usage: label [0-7] file1 [file2] ...
  Sets the Finder label (color) for files.
  Colors:
    0:  [no color]   4:  Blue
    1:  Orange       5:  Purple
    2:  Red          6:  Green
    3:  Yellow       7:  Gray"
	exit 1
fi

shift 2
argv=( "$@" )
color="$1"

# buffer data from stdin
#while read data; do
#	argv=( "$argv" "$data" )
#done

for i in "${argv[@]}"; do
	script="$script
	tell application \"Finder\"
		set theFile to POSIX file \"$i\"
		set label index of theFile to $color
	end tell"
done

#osascript -e '
#on run argv
#	set labelIndex to (item 1 of argv as number)
#	repeat with i from 2 to (count of argv)
#		tell application "Finder"
#			set theFile to POSIX file (item i of argv) as alias
#			set label index of theFile to labelIndex
#		end tell
#	end repeat
#end run' -- "$argv"

osascript -e "$script"