#!/bin/sh

SCRIPT=$(cat <<EOF

on run argv
	set filename to item 1 of argv
	
	tell application "QuickTime Player 7"
		open filename
		
		tell document 2
			copy
		end tell
		
		tell document 1 
			select at 0 to duration
			add scaled true
			rewind
			select none
		end tell
	
		save document 1
		close document 1
	end tell
	
	delay 0.2
end run

EOF
)

echo "Processing $# file(s):"

for FILE in "$@"
do	
	REALPATH=$(php -r "echo realpath('$FILE');")
	if [ -n "$REALPATH" -a -w "$REALPATH" ]; then
		echo "$REALPATH"
		osascript -e "$SCRIPT" "$REALPATH"
	else
		echo "$FILE"
		osascript -e "$SCRIPT" "$FILE"
	fi
done
